export const data = [
    {
         id: 1, nameProduct: "Vainilla a la Crema x kg", description: "Un clásico helado de vainilla con trozos de vainilla real y una cremosa textura.", img: "/images/Vainilla.jpg", price: 2000, quantity: 1},
        { id: 2, nameProduct: "Full Chocolate x kg", description: "Delicioso helado de chocolate con ricos trozos de chocolate negro.", img: "/images/ChocolateChips.jpg", price: 3000, quantity: 1 },
        { id: 3, nameProduct: "Frutilla a la Crema x kg", description: "Helado de frutillas fresca con trozos de fruta y un toque de acidez.", img: "/images/Frutillaalacrema.png", price: 2000, quantity: 1 },
        { id: 4, nameProduct: "Menta y Chocolate x kg", description: "Combinación perfecta de menta refrescante y trozos de chocolate.", img: "/images/Mentaychocolate.png", price: 3500, quantity: 1 },
        { id: 5, nameProduct: "Expresso de Café x kg", description: "Intenso helado de crema de café colombiano, ideal para los amantes de esta bebida.",img: "/images/Expressocafe.png", price: 3800, quantity: 1 },
        { id: 6, nameProduct: "Frambuesas del Valle x kg", description: "Helado de frambuesas orgánicas con un sabor afrutado y dulce.", img: "/images/Frambuesa.png", price: 3450, quantity: 1 },
        { id: 7, nameProduct: "Caramelo Salado x kg", description: "Cremoso helado de caramelo con un toque de sal marina.", img: "/images/Caramelosalado.png", price: 1900, quantity: 1 },
        { id: 8, nameProduct: "Avellanas y Frutos secos x kg", description: "Helado de avellana con trozos de nueces y almendras tostadas.", img: "/images/Avellayfrutos.png", price: 4000, quantity: 1 },
        { id: 9, nameProduct: "Coco Bongo x kg", description: "Refrescante helado de coco con trozos de coco rallado.", img: "/images/Cocobongo.png", price: 2200, quantity: 1 },
        { id: 10, nameProduct: "Limón al Agua x kg", description: "Helado de limón con un sabor cítrico y refrescante.", img: "/images/Limon.png", price: 1900, quantity: 1 },
        { id: 11, nameProduct: "Americana y Cookies x kg", description: "Helado de americana con trozos de galletitas cookies.", img: "/images/Americanaycookies.png", price: 3000, quantity: 1 },
        { id: 12, nameProduct: "Dulce de leche x kg", description: "Helado de dulce de leche con dulce de leche repostero por dentro.", img: "/images/Dulcedeleche.png", price: 3500, quantity: 1 },
        { id: 13, nameProduct: "Pistacho x kg", description: "Helado de pistacho con sabor a nuez y color verde vibrante.", img: "/images/Pistacho.png", price: 4500, quantity: 1 },
        { id: 14, nameProduct: "Banana Split x kg", description: "Helado de banana con dulce de leche artesanal.", img: "/images/BananaSplit.png", price:  2000, quantity: 1 },
        { id: 15, nameProduct: "Cereza al Rhum x kg", description: "Helado de cereza con trozos de cerezas rojas y un toque de nuestro delicioso rhum.", img: "/images/CerezaRhum.png", price: 3300, quantity: 1 },
        { id: 16, nameProduct: "ChocoMarroc x kg", description: "Helado de chocolate negro amargo con trozos de marroc y praline.", img: "/images/ChocoMarroc.png", price: 3900, quantity: 1 },
        { id: 17, nameProduct: "Mango Loco x kg", description: "Helado de mango con sabor tropical y trozos de mango maduro.", img: "/images/MangoLoco.png", price: 2700, quantity: 1 },
        { id: 18, nameProduct: "Frutos del Bosque x kg", description: "Mezcla de frutos del bosque en un helado cremoso.", img: "/images/frutosdelbosque.png", price: 3150, quantity: 1 },
        { id: 19, nameProduct: "India x kg", description: "Helado de canela con un toque de cardamomo y clavo de olor, super especiado y reconfortante.", img: "/images/India.png", price: 4150, quantity: 1 },
        { id: 20, nameProduct: "Kinotos al Whisky x kg", description: "Helado sabor vainilla con trozos enteros de kinotos remojados en nuestro mejor whisky Chival Regal.", img: "/images/Kinotoswhisky.png", price: 3400, quantity: 1 },
        { id: 21, nameProduct: "Tramontana x kg", description: "Helado con base de crema americana, un exquisito dulce de leche fresco y galletitas cubiertas de chocolate.", img: "/images/tramontana.png", price: 3250, quantity: 1 },
  ];